service:
  enabled: true
  port: 9003
  targetPort: 8083
  secrets:
    POSTGRES_PASSWORD: AgBDAiFig+uaucQInTjLdVSWV34Wid5Bx+Lg1LRkw2PF9yIo1CPKs9xStsGZjBZQI0l8EYuLv7t+WURYitTHMIpQflpGukOapAuVOVqkqtwOJ5DlUTrTm5/1IKnaZgHGQ3Y8jdUo4BDqMp7JSOe6AL9uVE0O1MSQHMJd/DAIbflYfxKosBT2oZfuWQdMzOHxr/DPOtmz7e8IcUZ37TuEkNToyliGeA3ynksWnsNW369uDVYWCaczXP1YjNnrsJgvk0tG2/R9eMyjQdmAZ/hbxZjfe36ofP2Zpql4fIX6jW5H2xR12T1k5wHSaHx5tXvkzFOS4FBBlAtI0vnfi8pClCQTJJcvCwxbI/VRtBs0Ag3Xbla6C3Z/YTeG1R4RPLVAiS+17D4iebG/pjVFw+2DbHKUWzi8VscYYjibfSHmCspCoT9+WoSr7gnKFb5tdsJ8uGbnb254FZFFbvS1pSTWoa3Ft2oTaOKfaZK+68xmBRux9HZHEV3D0UMjMhY7H1vzIYZ2YXJ0sf7s/dQC4DPqt7g1ekvndPteF1XXSWAj0aGl55kNFmmyzkdpGsLR6b/BkGB81LQ2ag8NRvdxOEmJHLigtmnSECYA1s+Tt4DRTrYGMrKWYhqIiyoOMOsxqlx625v9YII5I631VdayUGUlInwu3KclsXAWZkWIAVjHRviCzXLpmEfvOYuFk2onLzo1b99vWTifi1Eq9YDurx4tWcs3vROaJw4gS+lJWFi0665J3A==
    JWT_KEY: AgAL8MuIqSh6qtZaF9HtNiOeh/gSlHBhe+nv+O5WUhp6+Zw9ecSg9M2iulTKhkIewUK5Gg0Rlsw1ZYhR7pQL5DoAdGKvG7Jsg1AIKNi4j04tO6GqkQXw4zlGrv5L+3zQW2qfhY5EqlGLhCppsxxSSWUcRv/YJQ3pOJB2xluhDuXE8CC48z3y/mT9tGcQWp9K0YH1Ee9vguMVW1F5tCxJtuFz/dP1QYZ4jZ2tg46+DG8r+L9BvkF1nozh9+eO+63vemZAHkHGQEjc86Uc0FU0F84ZqFKV8g7Jg9LJkUj+3/v7Zq2Hn20FZ8EIUh/ff9e5jjfTd09Y3q/ftPAVZ0j4qgscRmHelyaPEmmPQYhRMWSA9lbCBGIET/ft5SXb4JhhZEL3yNXVXk9z+z39Yt4+ACPDo9y+pnPpNBzl1DaDIPcyxGN8hmyem1El69EUKv8aCEopY0HOvsMWxJnK57VKzTQVW+IM/VTOy8agRpsBudQIsrXIeiW6bgem90HW9p5cFBxD0so8uwXzCC9Ka4x3xbhtLS9wbtjhrzO/kHhp/tWE/Atwip2DYwU3A8SJovuw6vhEVAKOfhJvnLOL+TX/bcxQOruHxFR89mV1jIiVIPN8cnrz5XLqsWyRPsqVBgfHU+gW9dezXqqzYV+Pfqw7EP+cXakSr9CE9LArgByatmYXiBINfnwh4WjXHqikg8CuHr/fDYm81aKsUiGNUJwZ2K7R9fBk/ps2Mlamc7w4h0YqYNxBoqV5S2h0+bAz40mPHlOJNDjyRxdQJxB83MAGp00c
  postgresql:
    enabled: true
    auth:
      username: service_user
      database: notification_service
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: notification-service-postgresql.notification-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: notification_service
    POSTGRES_USER: service_user
