service:
  enabled: true
  port: 8002
  targetPort: 8083
  secrets:
    POSTGRES_PASSWORD: AgBeJHlPLgco9Ut8DifoYYZW7kxv2m6PHaWnlZlJVOpeRS1KFjmYPC9fs6WVL3SLRN0Cld/zIPtijiq01j8sw3Bsx0j5+Ia817FyC28Dg7gca8e0TaEu5r1rgF5Ih3v7BAlHG8wcWBLeDcUnMgn/5pCJliqAZWicucR5LcMyLYgbZayv/kJTmy+TnyOvp6qBj8W4x1xKdfiMVGyN2aVcDlKYyjgEih8nRyzVgbeMxux4x8I920EXCtIxSY/1XgKZdkM/e39niRtLiNa0nDjcPpB3otk+XsMk413J6rezswb2b2hr9Rk5hTf/N8CxomiXuhw9vZ+qTg7rharqaiNUCc0j/5totnNAnFAHtqu3i2P2C/TbXgHkgB+jp5Ne+ZFh7S3xwzT59buzmYL5g3+oR8NohWhdmAQJYRPYBvzEQAE72hWaA2tQ3VWZPaj6cUBoz4rIXy9DItf6Hw3w3ODhChE7VCiLlK4cs+nXd/7CKjgygJB8DG+ELEwuXJNL96P3UAjz03ZOScPudEbU/iZKYBfHSKb66nonoAC3vk6O4MDv0Ftnt/OPTRFa1UkYvMoY4jvVgQAb3BIcTv/oO8PeJpcitiscobOgIhz6fqx/GIbvN1tJxdDHOIymQp3j7T9BOKBau+dFf/WEiOz+ALbL78+R03QAUeDoP+NsmuGvNusPECxGGSSGm6NG3Xg5XEpx+UUpszlIIjktZEuJKD6Ha9eHxFDeL+GrGcI3ZZnymCvXdg==
    JWT_KEY: AgDYgdI5jg9gyGDsliVA/v8LJfwIQS8Jo+8jgoRCwXqeBqaPMsAl9xERAxn+9EyH+E5dkDLIc4sPgMYH+IHu22DFGUFfC8mYbiCYZ8uHKWwwVl576/6EZmrgkGOKqslH0jNw7xpr1bUr8Fwuz+/yEQVOaa4chXkFRoGVkcrLNdHPjBqGw/OiyRa9mZKATlaqkWYgu4DX4COPCZL0UJ8tJzfchb2Y/DQM/GPjJHq/t7tiwBWW88MNQ4ElViFAsEN1vvklKrt9y2cr06wQlIQSgw2xE/nIN5lfOS5KS4u83ArK4XUPWsdvqNBOnWPA/9UyvZ1Q2QU0ArQ0i/7UdhpUUKbEwEd2imOgsnEegufActkEyedTp1BmpQJiYhV7KfgBsjRYyFL6r3pON+CTuvjDu3oEoU7D6WRCZ0KFys2Kp/qxcc/eHjRLpI4AjetrDB91/IbpNbNyA11+ydeXRlFqsuFbNHyHvIdiV78X3Vd/Gi0bU769VaEqKnC4RCs3aGM2esfH6y1fno3sQoiVftfsvfijKqBEByEeYgwIXLKS5gIlO/Ak4Li8mSPe5bHhQ7v15ueSJdNlu9qfo4FqS6NRl9eVqEyEjo/eXt0jT3ETM5NLntZlsuv5OaXx2ln6s4i6416TT5/6HMltTRpf03c3zXw9vpLQBqLw2Gf4w8APGaQVkoEFyjQ9XL2C0IqG3XguUgAj8uyabQmEzQvciLu0DYjblqk//gmo/bw4Sm6w2F547JI83bcqga6/tvUkZhePOKH+X/wGKm8YYq6j9157Rfgm
  postgresql:
    enabled: true
    auth:
      username: service_user
      database: notification_service
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-bootstrap.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: notification-service-postgresql.image-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: notification_service
    POSTGRES_USER: service_user
