service:
  enabled: true
  port: 9003
  targetPort: 8083
  nodePort: 30104
  ingress:
    enabled: true
    paths:
      - /notification
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  consumer:
    enabled: true
  env:
    KAFKA_BOOTSTRAP_SERVERS: thirdplace-kafka-kafka-brokers.kafka.svc.cluster.local
    KAFKA_SECURITY_PROTOCOL:
    KAFKA_SASL_MECHANISM:
    KAFKA_SASL_USERNAME:
    KAFKA_SASL_PASSWORD:

    POSTGRES_HOST: notification-service-postgres.notification-service.svc.cluster.local
    POSTGRES_PORT: 5432
    POSTGRES_DBNAME: notification_service
    POSTGRES_USER: service_user
postgres:
  auth:
    username: service_user
    database: notification_service
