/*
 * Otto notification service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"time"
)

type Follow struct {
	Uuid      string    `json:"uuid"`
	User      User      `json:"user"`
	Following User      `json:"following"`
	DeletedAt time.Time `json:"deleted_at,omitempty"`
}

func DecodeMessageToFollow(message []byte) (*Follow, error) {
	follow := &Follow{}
	err := json.Unmarshal(message, follow)
	return follow, err
}
