/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import "encoding/json"

type PostLike struct {
	Post Post `json:"post"`

	User User `json:"user"`
}

func DecodeMessageToPostLike(message []byte) (*PostLike, error) {
	postLike := &PostLike{}
	err := json.Unmarshal(message, postLike)
	return postLike, err
}
