/*
 * Otto notification service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import "encoding/json"

type User struct {
	Uuid       string `json:"uuid"`
	Username   string `json:"username,omitempty"`
	Name       string `json:"name,omitempty"`
	ProfilePic string `json:"profile_pic,omitempty"`
	IsBanned   bool   `json:"is_banned,omitempty"`
}

func DecodeMessageToUser(message []byte) (*User, error) {
	user := &User{}
	err := json.Unmarshal(message, user)
	return user, err
}
