/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

import (
	"encoding/json"
	"net/http"
)

// NewSession struct for NewSession
type NewSession struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func DecodeRequestToNewSession(r *http.Request) (*NewSession, error) {
	decoder := json.NewDecoder(r.Body)
	var data *NewSession
	err := decoder.Decode(&data)
	if err != nil {
		return nil, err
	}
	return data, nil
}

func CreateNewSession(email string, password string) *NewSession {
	return &NewSession{
		Email:    email,
		Password: password,
	}
}
