/*
 * Otto user service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// User struct for User
type User struct {
	Id       int64  `json:"id"`
	Uuid     string `json:"uuid"`
	Name     string `json:"name"`
	Username string `json:"username"`
}
