on:
  push:
    branches:
      - main
jobs:
  run-tests:
    uses: third-place/actions/.github/workflows/run-go-tests.yaml@main
  publish-service-image:
    needs: run-tests
    uses: third-place/actions/.github/workflows/publish-docker-image.yaml@main
    secrets: inherit
    with:
      name: notification-service
      directory: .
      file: Dockerfile.service
  publish-consumer-image:
    needs: run-tests
    uses: third-place/actions/.github/workflows/publish-docker-image.yaml@main
    secrets: inherit
    with:
      name: notification-service-consumer
      directory: .
      dockerfile: Dockerfile.consumer
  deploy-service:
    needs: publish-service-image
    uses: third-place/actions/.github/workflows/deploy-env.yaml@main
    secrets: inherit
    with:
      name: notification-service
      env: dev
  deploy-consumer:
    needs: publish-consumer-image
    uses: third-place/actions/.github/workflows/deploy-env.yaml@main
    secrets: inherit
    with:
      name: notification-service-consumer
      env: dev
